defaults: &defaults
  docker:
    - image: circleci/node:8.10.0-browsers
  working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test:circleci
      - run: npm run publish:coverage
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - packages/*/node_modules
  license_test:
    <<: *defaults
    steps:
      - run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - run: fossa init
      - run: fossa analyze

  integration_test:
    <<: *defaults

    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm install
      - restore_cache:
          keys:
            - ddb-local-{{ checksum "package.json" }}
      - run: npm run test:integration
      - save_cache:
          paths:
            - /tmp/dynamodb-local
          key: ddb-local-{{ checksum "package.json" }}

workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - license_test:
          filters:
            branches:
              only: master
      - integration_test:
          requires:
            - build
