name: Test

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [master]
  merge_group:
  workflow_dispatch:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: 🧪 Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]
    permissions:
      id-token: write
      contents: read
      actions: write
    env:
      NODE_VERSION: ${{ matrix.node-version }}
      AWS_REGION: us-east-1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::211125641521:role/github-e2e-test
          aws-region: us-east-1

      - name: Run tests
        run: npm run test:all
